import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Regenerated by `npx convex dev` on every schema change — never hand-edited,
    // and it carries its own eslint-disable headers that we would otherwise flag.
    "convex/_generated/**",
  ]),
]);

export default eslintConfig;
