import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Regenerated by `npx convex dev` on every schema change — never hand-edited,
    // and it carries its own eslint-disable headers that we would otherwise flag.
    "convex/_generated/**",
    // Playwright's own output. Both are gitignored, but eslint does not read
    // .gitignore — and the HTML reporter ships a bundled trace viewer whose minified
    // assets are large enough to exhaust the linter's memory before it gives up.
    "playwright-report/**",
    "test-results/**",
    // Vendored agent skills, installed by tools like `uipro init` rather than written
    // here. They ship their own CommonJS helper scripts and Python, none of which this
    // project's TypeScript rules have any business judging — and none of which ship.
    ".claude/skills/**",
  ]),
]);

export default eslintConfig;
