// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  total: __t.i32(),
  playable: __t.i32(),
  byDifficulty: __t.array(__t.i32()).name("by_difficulty"),
  thinTiers: __t.array(__t.i32()).name("thin_tiers"),
  indexedTitles: __t.i32().name("indexed_titles"),
  indexTruncated: __t.bool().name("index_truncated"),
});
