// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ConfigOverride,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  get values() {
    return __t.array(ConfigOverride);
  },
  createdAt: __t.timestamp().name("created_at"),
  createdBy: __t.option(__t.u64()).name("created_by"),
  note: __t.option(__t.string()),
});
