// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  userId: __t.u64().name("user_id"),
  date: __t.string(),
  totalPoints: __t.f64().name("total_points"),
  perRoundMs: __t.array(__t.f64()).name("per_round_ms"),
  perRoundPoints: __t.array(__t.f64()).name("per_round_points"),
  completedAt: __t.timestamp().name("completed_at"),
  isGuest: __t.bool().name("is_guest"),
});
