// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  matchId: __t.u64().name("match_id"),
  roundIndex: __t.i32().name("round_index"),
  userId: __t.u64().name("user_id"),
  outcome: __t.string(),
  points: __t.f64(),
  rejectionReason: __t.option(__t.string()).name("rejection_reason"),
});
