// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.8.0 (commit 07aab11f9f256c8a18dd31308ad6ecac40341210).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import CompleteOnboardingReducer from "./complete_onboarding_reducer";
import EnsureUserReducer from "./ensure_user_reducer";
import NudgeReducer from "./nudge_reducer";
import PassRoundReducer from "./pass_round_reducer";
import ProbeHandleReducer from "./probe_handle_reducer";
import RebuildTitleIndexReducer from "./rebuild_title_index_reducer";
import RemoveAuthIssuerReducer from "./remove_auth_issuer_reducer";
import ReportReadyReducer from "./report_ready_reducer";
import ResetConfigReducer from "./reset_config_reducer";
import RevertConfigReducer from "./revert_config_reducer";
import SaveConfigReducer from "./save_config_reducer";
import SetAuthIssuerReducer from "./set_auth_issuer_reducer";
import SetDevFeaturesReducer from "./set_dev_features_reducer";
import SetHandleReducer from "./set_handle_reducer";
import SetRoleReducer from "./set_role_reducer";
import SetWelcomeStepReducer from "./set_welcome_step_reducer";
import SubmitGuessReducer from "./submit_guess_reducer";
import UpdateProfileReducer from "./update_profile_reducer";
import UpsertCategoriesReducer from "./upsert_categories_reducer";
import UpsertTracksReducer from "./upsert_tracks_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import CatalogueStatsRow from "./catalogue_stats_table";
import CategoryRow from "./category_table";
import CategoryRatingRow from "./category_rating_table";
import ConfigVersionRow from "./config_version_table";
import CurrentConfigVersionRow from "./current_config_version_table";
import DailyCountRow from "./daily_count_table";
import DailyRunRow from "./daily_run_table";
import GuessFeedbackRow from "./guess_feedback_table";
import LadderEntryRow from "./ladder_entry_table";
import LadderStatusRow from "./ladder_status_table";
import LadderTierCountRow from "./ladder_tier_count_table";
import MatchRow from "./match_table";
import MatchPlayerRow from "./match_player_table";
import MeRow from "./me_table";
import MyHandleProbeRow from "./my_handle_probe_table";
import MyRoundStatusRow from "./my_round_status_table";
import RoomRow from "./room_table";
import RoundLogRow from "./round_log_table";
import RoundResultRow from "./round_result_table";
import RoundRevealRow from "./round_reveal_table";
import SettingsRow from "./settings_table";
import TrackIndexRow from "./track_index_table";
import UserRow from "./user_table";
import UserBadgeRow from "./user_badge_table";
import UserPreferenceRow from "./user_preference_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  category: __table({
    name: 'category',
    indexes: [
      { accessor: 'id', name: 'category_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'slug', name: 'category_slug_idx_btree', algorithm: 'btree', columns: [
        'slug',
      ] },
    ],
    constraints: [
      { name: 'category_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'category_slug_key', constraint: 'unique', columns: ['slug'] },
    ],
  }, CategoryRow),
  categoryRating: __table({
    name: 'category_rating',
    indexes: [
      { accessor: 'id', name: 'category_rating_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_user_category', name: 'category_rating_user_id_category_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
        'categoryId',
      ] },
      { accessor: 'userId', name: 'category_rating_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'category_rating_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CategoryRatingRow),
  configVersion: __table({
    name: 'config_version',
    indexes: [
      { accessor: 'createdAt', name: 'config_version_created_at_idx_btree', algorithm: 'btree', columns: [
        'createdAt',
      ] },
      { accessor: 'id', name: 'config_version_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'config_version_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ConfigVersionRow),
  dailyCount: __table({
    name: 'daily_count',
    indexes: [
      { accessor: 'date', name: 'daily_count_date_idx_btree', algorithm: 'btree', columns: [
        'date',
      ] },
      { accessor: 'id', name: 'daily_count_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'daily_count_date_key', constraint: 'unique', columns: ['date'] },
      { name: 'daily_count_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DailyCountRow),
  dailyRun: __table({
    name: 'daily_run',
    indexes: [
      { accessor: 'date', name: 'daily_run_date_idx_btree', algorithm: 'btree', columns: [
        'date',
      ] },
      { accessor: 'by_date_points', name: 'daily_run_date_total_points_idx_btree', algorithm: 'btree', columns: [
        'date',
        'totalPoints',
      ] },
      { accessor: 'id', name: 'daily_run_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_user_date', name: 'daily_run_user_id_date_idx_btree', algorithm: 'btree', columns: [
        'userId',
        'date',
      ] },
      { accessor: 'userId', name: 'daily_run_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'daily_run_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DailyRunRow),
  guessFeedback: __table({
    name: 'guess_feedback',
    indexes: [
      { accessor: 'userId', name: 'guess_feedback_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
    ],
    event: true,
  }, GuessFeedbackRow),
  ladderEntry: __table({
    name: 'ladder_entry',
    indexes: [
      { accessor: 'rank', name: 'ladder_entry_rank_idx_btree', algorithm: 'btree', columns: [
        'rank',
      ] },
      { accessor: 'tierId', name: 'ladder_entry_tier_id_idx_btree', algorithm: 'btree', columns: [
        'tierId',
      ] },
      { accessor: 'userId', name: 'ladder_entry_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'ladder_entry_user_id_key', constraint: 'unique', columns: ['userId'] },
    ],
  }, LadderEntryRow),
  ladderStatus: __table({
    name: 'ladder_status',
    indexes: [
      { accessor: 'id', name: 'ladder_status_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'ladder_status_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, LadderStatusRow),
  ladderTierCount: __table({
    name: 'ladder_tier_count',
    indexes: [
      { accessor: 'tierId', name: 'ladder_tier_count_tier_id_idx_btree', algorithm: 'btree', columns: [
        'tierId',
      ] },
    ],
    constraints: [
      { name: 'ladder_tier_count_tier_id_key', constraint: 'unique', columns: ['tierId'] },
    ],
  }, LadderTierCountRow),
  match: __table({
    name: 'match',
    indexes: [
      { accessor: 'id', name: 'match_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_status', name: 'match_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'match_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MatchRow),
  matchPlayer: __table({
    name: 'match_player',
    indexes: [
      { accessor: 'id', name: 'match_player_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'matchId', name: 'match_player_match_id_idx_btree', algorithm: 'btree', columns: [
        'matchId',
      ] },
      { accessor: 'by_match_user', name: 'match_player_match_id_user_id_idx_btree', algorithm: 'btree', columns: [
        'matchId',
        'userId',
      ] },
      { accessor: 'userId', name: 'match_player_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'match_player_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MatchPlayerRow),
  room: __table({
    name: 'room',
    indexes: [
      { accessor: 'code', name: 'room_code_idx_btree', algorithm: 'btree', columns: [
        'code',
      ] },
      { accessor: 'id', name: 'room_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'room_code_key', constraint: 'unique', columns: ['code'] },
      { name: 'room_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RoomRow),
  roundLog: __table({
    name: 'round_log',
    indexes: [
      { accessor: 'id', name: 'round_log_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'matchId', name: 'round_log_match_id_idx_btree', algorithm: 'btree', columns: [
        'matchId',
      ] },
      { accessor: 'by_match_round', name: 'round_log_match_id_round_index_idx_btree', algorithm: 'btree', columns: [
        'matchId',
        'roundIndex',
      ] },
    ],
    constraints: [
      { name: 'round_log_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RoundLogRow),
  roundResult: __table({
    name: 'round_result',
    indexes: [
      { accessor: 'id', name: 'round_result_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'matchId', name: 'round_result_match_id_idx_btree', algorithm: 'btree', columns: [
        'matchId',
      ] },
      { accessor: 'by_match_round', name: 'round_result_match_id_round_index_idx_btree', algorithm: 'btree', columns: [
        'matchId',
        'roundIndex',
      ] },
      { accessor: 'by_match_round_user', name: 'round_result_match_id_round_index_user_id_idx_btree', algorithm: 'btree', columns: [
        'matchId',
        'roundIndex',
        'userId',
      ] },
    ],
    constraints: [
      { name: 'round_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RoundResultRow),
  roundReveal: __table({
    name: 'round_reveal',
    indexes: [
      { accessor: 'id', name: 'round_reveal_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'matchId', name: 'round_reveal_match_id_idx_btree', algorithm: 'btree', columns: [
        'matchId',
      ] },
      { accessor: 'by_match_round', name: 'round_reveal_match_id_round_index_idx_btree', algorithm: 'btree', columns: [
        'matchId',
        'roundIndex',
      ] },
    ],
    constraints: [
      { name: 'round_reveal_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RoundRevealRow),
  settings: __table({
    name: 'settings',
    indexes: [
      { accessor: 'id', name: 'settings_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'settings_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SettingsRow),
  trackIndex: __table({
    name: 'track_index',
    indexes: [
      { accessor: 'id', name: 'track_index_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'track_index_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TrackIndexRow),
  user: __table({
    name: 'user',
    indexes: [
      { accessor: 'elo', name: 'user_elo_idx_btree', algorithm: 'btree', columns: [
        'elo',
      ] },
      { accessor: 'handle', name: 'user_handle_idx_btree', algorithm: 'btree', columns: [
        'handle',
      ] },
      { accessor: 'id', name: 'user_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'isBot', name: 'user_is_bot_idx_btree', algorithm: 'btree', columns: [
        'isBot',
      ] },
      { accessor: 'isGuest', name: 'user_is_guest_idx_btree', algorithm: 'btree', columns: [
        'isGuest',
      ] },
    ],
    constraints: [
      { name: 'user_handle_key', constraint: 'unique', columns: ['handle'] },
      { name: 'user_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UserRow),
  userBadge: __table({
    name: 'user_badge',
    indexes: [
      { accessor: 'id', name: 'user_badge_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_user_badge', name: 'user_badge_user_id_badge_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
        'badgeId',
      ] },
      { accessor: 'userId', name: 'user_badge_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'user_badge_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UserBadgeRow),
  userPreference: __table({
    name: 'user_preference',
    indexes: [
      { accessor: 'userId', name: 'user_preference_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'user_preference_user_id_key', constraint: 'unique', columns: ['userId'] },
    ],
  }, UserPreferenceRow),
  catalogueStats: __table({
    name: 'catalogue_stats',
    indexes: [
    ],
    constraints: [
    ],
  }, CatalogueStatsRow),
  currentConfigVersion: __table({
    name: 'current_config_version',
    indexes: [
    ],
    constraints: [
    ],
  }, CurrentConfigVersionRow),
  me: __table({
    name: 'me',
    indexes: [
    ],
    constraints: [
    ],
  }, MeRow),
  myHandleProbe: __table({
    name: 'my_handle_probe',
    indexes: [
    ],
    constraints: [
    ],
  }, MyHandleProbeRow),
  myRoundStatus: __table({
    name: 'my_round_status',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRoundStatusRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("complete_onboarding", CompleteOnboardingReducer),
  __reducerSchema("ensure_user", EnsureUserReducer),
  __reducerSchema("nudge", NudgeReducer),
  __reducerSchema("pass_round", PassRoundReducer),
  __reducerSchema("probe_handle", ProbeHandleReducer),
  __reducerSchema("rebuild_title_index", RebuildTitleIndexReducer),
  __reducerSchema("remove_auth_issuer", RemoveAuthIssuerReducer),
  __reducerSchema("report_ready", ReportReadyReducer),
  __reducerSchema("reset_config", ResetConfigReducer),
  __reducerSchema("revert_config", RevertConfigReducer),
  __reducerSchema("save_config", SaveConfigReducer),
  __reducerSchema("set_auth_issuer", SetAuthIssuerReducer),
  __reducerSchema("set_dev_features", SetDevFeaturesReducer),
  __reducerSchema("set_handle", SetHandleReducer),
  __reducerSchema("set_role", SetRoleReducer),
  __reducerSchema("set_welcome_step", SetWelcomeStepReducer),
  __reducerSchema("submit_guess", SubmitGuessReducer),
  __reducerSchema("update_profile", UpdateProfileReducer),
  __reducerSchema("upsert_categories", UpsertCategoriesReducer),
  __reducerSchema("upsert_tracks", UpsertTracksReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

type __SchemaWithTableAccessorAliases = Omit<typeof tablesSchema.schemaType, "tables"> & {
  tables: typeof tablesSchema.schemaType.tables & {
    /** @deprecated Use `categoryRating` instead. This alias will be removed in the next major version. */
    readonly "category_rating": Omit<typeof tablesSchema.schemaType.tables["categoryRating"], "accessorName"> & { readonly accessorName: "category_rating" };
    /** @deprecated Use `configVersion` instead. This alias will be removed in the next major version. */
    readonly "config_version": Omit<typeof tablesSchema.schemaType.tables["configVersion"], "accessorName"> & { readonly accessorName: "config_version" };
    /** @deprecated Use `dailyCount` instead. This alias will be removed in the next major version. */
    readonly "daily_count": Omit<typeof tablesSchema.schemaType.tables["dailyCount"], "accessorName"> & { readonly accessorName: "daily_count" };
    /** @deprecated Use `dailyRun` instead. This alias will be removed in the next major version. */
    readonly "daily_run": Omit<typeof tablesSchema.schemaType.tables["dailyRun"], "accessorName"> & { readonly accessorName: "daily_run" };
    /** @deprecated Use `guessFeedback` instead. This alias will be removed in the next major version. */
    readonly "guess_feedback": Omit<typeof tablesSchema.schemaType.tables["guessFeedback"], "accessorName"> & { readonly accessorName: "guess_feedback" };
    /** @deprecated Use `ladderEntry` instead. This alias will be removed in the next major version. */
    readonly "ladder_entry": Omit<typeof tablesSchema.schemaType.tables["ladderEntry"], "accessorName"> & { readonly accessorName: "ladder_entry" };
    /** @deprecated Use `ladderStatus` instead. This alias will be removed in the next major version. */
    readonly "ladder_status": Omit<typeof tablesSchema.schemaType.tables["ladderStatus"], "accessorName"> & { readonly accessorName: "ladder_status" };
    /** @deprecated Use `ladderTierCount` instead. This alias will be removed in the next major version. */
    readonly "ladder_tier_count": Omit<typeof tablesSchema.schemaType.tables["ladderTierCount"], "accessorName"> & { readonly accessorName: "ladder_tier_count" };
    /** @deprecated Use `matchPlayer` instead. This alias will be removed in the next major version. */
    readonly "match_player": Omit<typeof tablesSchema.schemaType.tables["matchPlayer"], "accessorName"> & { readonly accessorName: "match_player" };
    /** @deprecated Use `roundLog` instead. This alias will be removed in the next major version. */
    readonly "round_log": Omit<typeof tablesSchema.schemaType.tables["roundLog"], "accessorName"> & { readonly accessorName: "round_log" };
    /** @deprecated Use `roundResult` instead. This alias will be removed in the next major version. */
    readonly "round_result": Omit<typeof tablesSchema.schemaType.tables["roundResult"], "accessorName"> & { readonly accessorName: "round_result" };
    /** @deprecated Use `roundReveal` instead. This alias will be removed in the next major version. */
    readonly "round_reveal": Omit<typeof tablesSchema.schemaType.tables["roundReveal"], "accessorName"> & { readonly accessorName: "round_reveal" };
    /** @deprecated Use `trackIndex` instead. This alias will be removed in the next major version. */
    readonly "track_index": Omit<typeof tablesSchema.schemaType.tables["trackIndex"], "accessorName"> & { readonly accessorName: "track_index" };
    /** @deprecated Use `userBadge` instead. This alias will be removed in the next major version. */
    readonly "user_badge": Omit<typeof tablesSchema.schemaType.tables["userBadge"], "accessorName"> & { readonly accessorName: "user_badge" };
    /** @deprecated Use `userPreference` instead. This alias will be removed in the next major version. */
    readonly "user_preference": Omit<typeof tablesSchema.schemaType.tables["userPreference"], "accessorName"> & { readonly accessorName: "user_preference" };
  };
};

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.8.0" as const,
  },
  tables: tablesSchema.schemaType.tables as __SchemaWithTableAccessorAliases["tables"],
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  __SchemaWithTableAccessorAliases,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

const tableAccessorAliases = {
  "category_rating": "categoryRating",
  "config_version": "configVersion",
  "daily_count": "dailyCount",
  "daily_run": "dailyRun",
  "guess_feedback": "guessFeedback",
  "ladder_entry": "ladderEntry",
  "ladder_status": "ladderStatus",
  "ladder_tier_count": "ladderTierCount",
  "match_player": "matchPlayer",
  "round_log": "roundLog",
  "round_result": "roundResult",
  "round_reveal": "roundReveal",
  "track_index": "trackIndex",
  "user_badge": "userBadge",
  "user_preference": "userPreference",
} as const;

function __withTableAccessorAliases<T extends object>(target: T, freeze = false): T {
  const out = Object.create(Object.getPrototypeOf(target)) as T & Record<string, unknown>;
  Object.defineProperties(out, Object.getOwnPropertyDescriptors(target));
  for (const [deprecatedAccessor, targetAccessor] of Object.entries(tableAccessorAliases)) {
    if (deprecatedAccessor in out) {
      continue;
    }
    Object.defineProperty(out, deprecatedAccessor, {
      enumerable: true,
      configurable: false,
      get: () => out[targetAccessor],
    });
  }
  return freeze ? Object.freeze(out) : out;
}

type __DbViewBase = __DbConnectionImpl<typeof REMOTE_MODULE>["db"];
export type DbView = __DbViewBase & {
  /** @deprecated Use `categoryRating` instead. This alias will be removed in the next major version. */
  readonly "category_rating": __DbViewBase["categoryRating"];
  /** @deprecated Use `configVersion` instead. This alias will be removed in the next major version. */
  readonly "config_version": __DbViewBase["configVersion"];
  /** @deprecated Use `dailyCount` instead. This alias will be removed in the next major version. */
  readonly "daily_count": __DbViewBase["dailyCount"];
  /** @deprecated Use `dailyRun` instead. This alias will be removed in the next major version. */
  readonly "daily_run": __DbViewBase["dailyRun"];
  /** @deprecated Use `guessFeedback` instead. This alias will be removed in the next major version. */
  readonly "guess_feedback": __DbViewBase["guessFeedback"];
  /** @deprecated Use `ladderEntry` instead. This alias will be removed in the next major version. */
  readonly "ladder_entry": __DbViewBase["ladderEntry"];
  /** @deprecated Use `ladderStatus` instead. This alias will be removed in the next major version. */
  readonly "ladder_status": __DbViewBase["ladderStatus"];
  /** @deprecated Use `ladderTierCount` instead. This alias will be removed in the next major version. */
  readonly "ladder_tier_count": __DbViewBase["ladderTierCount"];
  /** @deprecated Use `matchPlayer` instead. This alias will be removed in the next major version. */
  readonly "match_player": __DbViewBase["matchPlayer"];
  /** @deprecated Use `roundLog` instead. This alias will be removed in the next major version. */
  readonly "round_log": __DbViewBase["roundLog"];
  /** @deprecated Use `roundResult` instead. This alias will be removed in the next major version. */
  readonly "round_result": __DbViewBase["roundResult"];
  /** @deprecated Use `roundReveal` instead. This alias will be removed in the next major version. */
  readonly "round_reveal": __DbViewBase["roundReveal"];
  /** @deprecated Use `trackIndex` instead. This alias will be removed in the next major version. */
  readonly "track_index": __DbViewBase["trackIndex"];
  /** @deprecated Use `userBadge` instead. This alias will be removed in the next major version. */
  readonly "user_badge": __DbViewBase["userBadge"];
  /** @deprecated Use `userPreference` instead. This alias will be removed in the next major version. */
  readonly "user_preference": __DbViewBase["userPreference"];
};

type __TablesBase = __QueryBuilder<typeof tablesSchema.schemaType>;
export type Tables = __TablesBase & {
  /** @deprecated Use `categoryRating` instead. This alias will be removed in the next major version. */
  readonly "category_rating": __TablesBase["categoryRating"];
  /** @deprecated Use `configVersion` instead. This alias will be removed in the next major version. */
  readonly "config_version": __TablesBase["configVersion"];
  /** @deprecated Use `dailyCount` instead. This alias will be removed in the next major version. */
  readonly "daily_count": __TablesBase["dailyCount"];
  /** @deprecated Use `dailyRun` instead. This alias will be removed in the next major version. */
  readonly "daily_run": __TablesBase["dailyRun"];
  /** @deprecated Use `guessFeedback` instead. This alias will be removed in the next major version. */
  readonly "guess_feedback": __TablesBase["guessFeedback"];
  /** @deprecated Use `ladderEntry` instead. This alias will be removed in the next major version. */
  readonly "ladder_entry": __TablesBase["ladderEntry"];
  /** @deprecated Use `ladderStatus` instead. This alias will be removed in the next major version. */
  readonly "ladder_status": __TablesBase["ladderStatus"];
  /** @deprecated Use `ladderTierCount` instead. This alias will be removed in the next major version. */
  readonly "ladder_tier_count": __TablesBase["ladderTierCount"];
  /** @deprecated Use `matchPlayer` instead. This alias will be removed in the next major version. */
  readonly "match_player": __TablesBase["matchPlayer"];
  /** @deprecated Use `roundLog` instead. This alias will be removed in the next major version. */
  readonly "round_log": __TablesBase["roundLog"];
  /** @deprecated Use `roundResult` instead. This alias will be removed in the next major version. */
  readonly "round_result": __TablesBase["roundResult"];
  /** @deprecated Use `roundReveal` instead. This alias will be removed in the next major version. */
  readonly "round_reveal": __TablesBase["roundReveal"];
  /** @deprecated Use `trackIndex` instead. This alias will be removed in the next major version. */
  readonly "track_index": __TablesBase["trackIndex"];
  /** @deprecated Use `userBadge` instead. This alias will be removed in the next major version. */
  readonly "user_badge": __TablesBase["userBadge"];
  /** @deprecated Use `userPreference` instead. This alias will be removed in the next major version. */
  readonly "user_preference": __TablesBase["userPreference"];
};

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
const tablesBase: __TablesBase = __makeQueryBuilder(tablesSchema.schemaType);
export const tables: Tables = __withTableAccessorAliases(tablesBase, true) as Tables;

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = Omit<__EventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = Omit<__ReducerEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = Omit<__SubscriptionEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for error events. */
export type ErrorContext = Omit<__ErrorContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  declare db: DbView;

  constructor(config: __DbConnectionConfig<typeof REMOTE_MODULE>) {
    super(config);
    this.db = __withTableAccessorAliases(this.db) as DbView;
  }

  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

