// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  userId: __t.u64().primaryKey().name("user_id"),
  rank: __t.i32(),
  elo: __t.i32(),
  handle: __t.string(),
  displayName: __t.string().name("display_name"),
  avatarUrl: __t.option(__t.string()).name("avatar_url"),
  gamesPlayed: __t.i32().name("games_played"),
  level: __t.i32(),
  tierId: __t.string().name("tier_id"),
  approximate: __t.bool(),
});
