// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  mode: __t.string(),
  status: __t.string(),
  playerIds: __t.array(__t.u64()).name("player_ids"),
  totalRounds: __t.i32().name("total_rounds"),
  bannedCategoryIds: __t.array(__t.u64()).name("banned_category_ids"),
  vetoPoolIds: __t.array(__t.u64()).name("veto_pool_ids"),
  vetoDeadline: __t.option(__t.timestamp()).name("veto_deadline"),
  banOrder: __t.array(__t.u64()).name("ban_order"),
  banTurn: __t.i32().name("ban_turn"),
  currentRound: __t.i32().name("current_round"),
  roundStartedAt: __t.option(__t.timestamp()).name("round_started_at"),
  phase: __t.string(),
  phaseEndsAt: __t.option(__t.timestamp()).name("phase_ends_at"),
  suddenDeath: __t.bool().name("sudden_death"),
  roomId: __t.option(__t.u64()).name("room_id"),
  winnerId: __t.option(__t.u64()).name("winner_id"),
  createdAt: __t.timestamp().name("created_at"),
  completedAt: __t.option(__t.timestamp()).name("completed_at"),
  configVersionId: __t.option(__t.u64()).name("config_version_id"),
});
