// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  XpAward,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  matchId: __t.u64().name("match_id"),
  userId: __t.u64().name("user_id"),
  totalPoints: __t.f64().name("total_points"),
  ratingBefore: __t.i32().name("rating_before"),
  globalRankAtStart: __t.option(__t.i32()).name("global_rank_at_start"),
  ratingAfter: __t.option(__t.i32()).name("rating_after"),
  ratingDelta: __t.option(__t.i32()).name("rating_delta"),
  bannedCategoryIds: __t.array(__t.u64()).name("banned_category_ids"),
  hasBanned: __t.bool().name("has_banned"),
  hp: __t.f64(),
  lowestHp: __t.f64().name("lowest_hp"),
  eliminatedAtRound: __t.option(__t.i32()).name("eliminated_at_round"),
  readyForRound: __t.i32().name("ready_for_round"),
  vsReadyAt: __t.option(__t.timestamp()).name("vs_ready_at"),
  passedRound: __t.option(__t.i32()).name("passed_round"),
  xpEarned: __t.f64().name("xp_earned"),
  get xpBreakdown() {
    return __t.array(XpAward).name("xp_breakdown");
  },
  levelBefore: __t.option(__t.i32()).name("level_before"),
  levelAfter: __t.option(__t.i32()).name("level_after"),
  xpAfter: __t.option(__t.f64()).name("xp_after"),
  badgesEarned: __t.array(__t.string()).name("badges_earned"),
  forfeited: __t.bool(),
  mode: __t.option(__t.string()),
  completedAt: __t.option(__t.timestamp()).name("completed_at"),
  outcome: __t.option(__t.string()),
  opponentId: __t.option(__t.u64()).name("opponent_id"),
});
