// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  matchId: __t.u64().name("match_id"),
  roundIndex: __t.i32().name("round_index"),
  solved: __t.bool(),
  attempts: __t.i32(),
  attemptsRemaining: __t.i32().name("attempts_remaining"),
  lockedUntil: __t.option(__t.timestamp()).name("locked_until"),
  pointsThisRound: __t.f64().name("points_this_round"),
  passed: __t.bool(),
});
