// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  code: __t.string(),
  hostId: __t.u64().name("host_id"),
  memberIds: __t.array(__t.u64()).name("member_ids"),
  status: __t.string(),
  activeMatchId: __t.option(__t.u64()).name("active_match_id"),
  readyIds: __t.array(__t.u64()).name("ready_ids"),
  createdAt: __t.timestamp().name("created_at"),
});
