// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  matchId: __t.u64().name("match_id"),
  roundIndex: __t.i32().name("round_index"),
  previewUrl: __t.string().name("preview_url"),
  title: __t.option(__t.string()),
  artist: __t.option(__t.string()),
  artworkUrl: __t.option(__t.string()).name("artwork_url"),
  categoryName: __t.option(__t.string()).name("category_name"),
  revealedAt: __t.option(__t.timestamp()).name("revealed_at"),
});
