// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  currentVersionId: __t.option(__t.u64()).name("current_version_id"),
  devFeaturesEnabled: __t.bool().name("dev_features_enabled"),
  updatedAt: __t.timestamp().name("updated_at"),
  updatedBy: __t.option(__t.u64()).name("updated_by"),
});
