// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  identity: __t.identity(),
  userId: __t.u64(),
  issuer: __t.string(),
  createdAt: __t.timestamp(),
});
export type Account = __Infer<typeof Account>;

export const AuthIssuer = __t.object("AuthIssuer", {
  issuer: __t.string(),
  audience: __t.string(),
  addedAt: __t.timestamp(),
});
export type AuthIssuer = __Infer<typeof AuthIssuer>;

export const BotActionSchedule = __t.object("BotActionSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  matchId: __t.u64(),
  userId: __t.u64(),
  kind: __t.string(),
  roundIndex: __t.i32(),
  expectedTurn: __t.i32(),
  text: __t.string(),
  clientElapsedMs: __t.f64(),
});
export type BotActionSchedule = __Infer<typeof BotActionSchedule>;

export const CatalogueHealth = __t.object("CatalogueHealth", {
  total: __t.i32(),
  playable: __t.i32(),
  byDifficulty: __t.array(__t.i32()),
  thinTiers: __t.array(__t.i32()),
  indexedTitles: __t.i32(),
  indexTruncated: __t.bool(),
});
export type CatalogueHealth = __Infer<typeof CatalogueHealth>;

export const CatalogueStats = __t.object("CatalogueStats", {});
export type CatalogueStats = __Infer<typeof CatalogueStats>;

export const Category = __t.object("Category", {
  id: __t.u64(),
  slug: __t.string(),
  name: __t.string(),
  sortOrder: __t.i32(),
});
export type Category = __Infer<typeof Category>;

export const CategoryInput = __t.object("CategoryInput", {
  slug: __t.string(),
  name: __t.string(),
  sortOrder: __t.i32(),
});
export type CategoryInput = __Infer<typeof CategoryInput>;

export const CategoryRating = __t.object("CategoryRating", {
  id: __t.u64(),
  userId: __t.u64(),
  categoryId: __t.u64(),
  rating: __t.f64(),
  games: __t.i32(),
});
export type CategoryRating = __Infer<typeof CategoryRating>;

export const ConfigOverride = __t.object("ConfigOverride", {
  key: __t.string(),
  value: __t.option(__t.f64()),
});
export type ConfigOverride = __Infer<typeof ConfigOverride>;

export const ConfigPointer = __t.object("ConfigPointer", {
  versionId: __t.option(__t.u64()),
  devFeaturesEnabled: __t.bool(),
});
export type ConfigPointer = __Infer<typeof ConfigPointer>;

export const ConfigVersion = __t.object("ConfigVersion", {
  id: __t.u64(),
  get values() {
    return __t.array(ConfigOverride);
  },
  createdAt: __t.timestamp(),
  createdBy: __t.option(__t.u64()),
  note: __t.option(__t.string()),
});
export type ConfigVersion = __Infer<typeof ConfigVersion>;

export const Connection = __t.object("Connection", {
  connectionId: __t.connectionId(),
  identity: __t.identity(),
  connectedAt: __t.timestamp(),
});
export type Connection = __Infer<typeof Connection>;

export const CurrentConfigVersion = __t.object("CurrentConfigVersion", {});
export type CurrentConfigVersion = __Infer<typeof CurrentConfigVersion>;

export const DailyChallenge = __t.object("DailyChallenge", {
  id: __t.u64(),
  date: __t.string(),
  trackIds: __t.array(__t.u64()),
});
export type DailyChallenge = __Infer<typeof DailyChallenge>;

export const DailyCount = __t.object("DailyCount", {
  id: __t.u64(),
  date: __t.string(),
  players: __t.i32(),
});
export type DailyCount = __Infer<typeof DailyCount>;

export const DailyRun = __t.object("DailyRun", {
  id: __t.u64(),
  userId: __t.u64(),
  date: __t.string(),
  totalPoints: __t.f64(),
  perRoundMs: __t.array(__t.f64()),
  perRoundPoints: __t.array(__t.f64()),
  completedAt: __t.timestamp(),
  isGuest: __t.bool(),
});
export type DailyRun = __Infer<typeof DailyRun>;

export const DevbotRefillSchedule = __t.object("DevbotRefillSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type DevbotRefillSchedule = __Infer<typeof DevbotRefillSchedule>;

export const DraftWatchdogSchedule = __t.object("DraftWatchdogSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  matchId: __t.u64(),
});
export type DraftWatchdogSchedule = __Infer<typeof DraftWatchdogSchedule>;

export const FinalizeSchedule = __t.object("FinalizeSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  matchId: __t.u64(),
});
export type FinalizeSchedule = __Infer<typeof FinalizeSchedule>;

export const ForfeitSweepSchedule = __t.object("ForfeitSweepSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  matchId: __t.u64(),
});
export type ForfeitSweepSchedule = __Infer<typeof ForfeitSweepSchedule>;

export const Guess = __t.object("Guess", {
  id: __t.u64(),
  matchId: __t.u64(),
  roundIndex: __t.i32(),
  userId: __t.u64(),
  rawText: __t.string(),
  normalizedText: __t.string(),
  correct: __t.bool(),
  clientElapsedMs: __t.f64(),
  serverReceivedAt: __t.timestamp(),
  accepted: __t.bool(),
  rejectionReason: __t.option(__t.string()),
  points: __t.f64(),
});
export type Guess = __Infer<typeof Guess>;

export const GuessFeedback = __t.object("GuessFeedback", {
  matchId: __t.u64(),
  roundIndex: __t.i32(),
  userId: __t.u64(),
  outcome: __t.string(),
  points: __t.f64(),
  rejectionReason: __t.option(__t.string()),
});
export type GuessFeedback = __Infer<typeof GuessFeedback>;

export const GuestCleanupSchedule = __t.object("GuestCleanupSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type GuestCleanupSchedule = __Infer<typeof GuestCleanupSchedule>;

export const HandleAvailability = __t.object("HandleAvailability", {
  handle: __t.string(),
  available: __t.bool(),
  reason: __t.string(),
});
export type HandleAvailability = __Infer<typeof HandleAvailability>;

export const HandleProbe = __t.object("HandleProbe", {
  userId: __t.u64(),
  candidate: __t.string(),
  probedAt: __t.timestamp(),
});
export type HandleProbe = __Infer<typeof HandleProbe>;

export const LadderEntry = __t.object("LadderEntry", {
  userId: __t.u64(),
  rank: __t.i32(),
  elo: __t.i32(),
  handle: __t.string(),
  displayName: __t.string(),
  avatarUrl: __t.option(__t.string()),
  gamesPlayed: __t.i32(),
  level: __t.i32(),
  tierId: __t.string(),
  approximate: __t.bool(),
});
export type LadderEntry = __Infer<typeof LadderEntry>;

export const LadderRebuildSchedule = __t.object("LadderRebuildSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type LadderRebuildSchedule = __Infer<typeof LadderRebuildSchedule>;

export const LadderStatus = __t.object("LadderStatus", {
  id: __t.u64(),
  playerCount: __t.i32(),
  truncated: __t.bool(),
  builtAt: __t.timestamp(),
  checkedAt: __t.timestamp(),
});
export type LadderStatus = __Infer<typeof LadderStatus>;

export const LadderTierCount = __t.object("LadderTierCount", {
  tierId: __t.string(),
  count: __t.i32(),
});
export type LadderTierCount = __Infer<typeof LadderTierCount>;

export const Match = __t.object("Match", {
  id: __t.u64(),
  mode: __t.string(),
  status: __t.string(),
  playerIds: __t.array(__t.u64()),
  totalRounds: __t.i32(),
  bannedCategoryIds: __t.array(__t.u64()),
  vetoPoolIds: __t.array(__t.u64()),
  vetoDeadline: __t.option(__t.timestamp()),
  banOrder: __t.array(__t.u64()),
  banTurn: __t.i32(),
  currentRound: __t.i32(),
  roundStartedAt: __t.option(__t.timestamp()),
  phase: __t.string(),
  phaseEndsAt: __t.option(__t.timestamp()),
  suddenDeath: __t.bool(),
  roomId: __t.option(__t.u64()),
  winnerId: __t.option(__t.u64()),
  createdAt: __t.timestamp(),
  completedAt: __t.option(__t.timestamp()),
  configVersionId: __t.option(__t.u64()),
});
export type Match = __Infer<typeof Match>;

export const MatchPlayer = __t.object("MatchPlayer", {
  id: __t.u64(),
  matchId: __t.u64(),
  userId: __t.u64(),
  totalPoints: __t.f64(),
  ratingBefore: __t.i32(),
  globalRankAtStart: __t.option(__t.i32()),
  ratingAfter: __t.option(__t.i32()),
  ratingDelta: __t.option(__t.i32()),
  bannedCategoryIds: __t.array(__t.u64()),
  hasBanned: __t.bool(),
  hp: __t.f64(),
  lowestHp: __t.f64(),
  eliminatedAtRound: __t.option(__t.i32()),
  readyForRound: __t.i32(),
  vsReadyAt: __t.option(__t.timestamp()),
  passedRound: __t.option(__t.i32()),
  xpEarned: __t.f64(),
  get xpBreakdown() {
    return __t.array(XpAward);
  },
  levelBefore: __t.option(__t.i32()),
  levelAfter: __t.option(__t.i32()),
  xpAfter: __t.option(__t.f64()),
  badgesEarned: __t.array(__t.string()),
  forfeited: __t.bool(),
  mode: __t.option(__t.string()),
  completedAt: __t.option(__t.timestamp()),
  outcome: __t.option(__t.string()),
  opponentId: __t.option(__t.u64()),
});
export type MatchPlayer = __Infer<typeof MatchPlayer>;

export const MatchTrack = __t.object("MatchTrack", {
  id: __t.u64(),
  matchId: __t.u64(),
  roundIndex: __t.i32(),
  trackId: __t.u64(),
});
export type MatchTrack = __Infer<typeof MatchTrack>;

export const MatchmakingSweepSchedule = __t.object("MatchmakingSweepSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MatchmakingSweepSchedule = __Infer<typeof MatchmakingSweepSchedule>;

export const Me = __t.object("Me", {});
export type Me = __Infer<typeof Me>;

export const ModuleOwner = __t.object("ModuleOwner", {
  identity: __t.identity(),
  capturedAt: __t.timestamp(),
});
export type ModuleOwner = __Infer<typeof ModuleOwner>;

export const MyHandleProbe = __t.object("MyHandleProbe", {});
export type MyHandleProbe = __Infer<typeof MyHandleProbe>;

export const MyQueueStatus = __t.object("MyQueueStatus", {});
export type MyQueueStatus = __Infer<typeof MyQueueStatus>;

export const MyRoundStatus = __t.object("MyRoundStatus", {});
export type MyRoundStatus = __Infer<typeof MyRoundStatus>;

export const OverrideInput = __t.object("OverrideInput", {
  key: __t.string(),
  value: __t.option(__t.f64()),
});
export type OverrideInput = __Infer<typeof OverrideInput>;

export const PhaseAdvanceSchedule = __t.object("PhaseAdvanceSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  matchId: __t.u64(),
  expectedPhase: __t.string(),
  expectedRound: __t.i32(),
});
export type PhaseAdvanceSchedule = __Infer<typeof PhaseAdvanceSchedule>;

export const QueueEntry = __t.object("QueueEntry", {
  userId: __t.u64(),
  elo: __t.i32(),
  enqueuedAt: __t.timestamp(),
  isBot: __t.bool(),
});
export type QueueEntry = __Infer<typeof QueueEntry>;

export const QueueStanding = __t.object("QueueStanding", {
  queued: __t.bool(),
  enqueuedAt: __t.option(__t.timestamp()),
  playersWaiting: __t.i32(),
});
export type QueueStanding = __Infer<typeof QueueStanding>;

export const ReadyWaitSchedule = __t.object("ReadyWaitSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  matchId: __t.u64(),
  roundIndex: __t.i32(),
  startedWaitingAt: __t.timestamp(),
});
export type ReadyWaitSchedule = __Infer<typeof ReadyWaitSchedule>;

export const Report = __t.object("Report", {
  id: __t.u64(),
  reportedUserId: __t.u64(),
  reporterUserId: __t.u64(),
  kind: __t.string(),
  reason: __t.string(),
  createdAt: __t.timestamp(),
  resolvedAt: __t.option(__t.timestamp()),
});
export type Report = __Infer<typeof Report>;

export const Room = __t.object("Room", {
  id: __t.u64(),
  code: __t.string(),
  hostId: __t.u64(),
  memberIds: __t.array(__t.u64()),
  status: __t.string(),
  activeMatchId: __t.option(__t.u64()),
  readyIds: __t.array(__t.u64()),
  createdAt: __t.timestamp(),
});
export type Room = __Infer<typeof Room>;

export const RoundDamage = __t.object("RoundDamage", {
  userId: __t.u64(),
  damage: __t.f64(),
  hpAfter: __t.f64(),
});
export type RoundDamage = __Infer<typeof RoundDamage>;

export const RoundLog = __t.object("RoundLog", {
  id: __t.u64(),
  matchId: __t.u64(),
  roundIndex: __t.i32(),
  get entry() {
    return RoundLogEntry;
  },
});
export type RoundLog = __Infer<typeof RoundLog>;

export const RoundLogEntry = __t.object("RoundLogEntry", {
  roundIndex: __t.i32(),
  outcome: __t.string(),
  winnerId: __t.option(__t.u64()),
  timeGapMs: __t.option(__t.f64()),
  multiplier: __t.f64(),
  get damage() {
    return __t.array(RoundDamage);
  },
  get results() {
    return __t.array(RoundPlayerResult);
  },
});
export type RoundLogEntry = __Infer<typeof RoundLogEntry>;

export const RoundPlayerResult = __t.object("RoundPlayerResult", {
  userId: __t.u64(),
  points: __t.f64(),
  elapsedMs: __t.option(__t.f64()),
  solved: __t.bool(),
});
export type RoundPlayerResult = __Infer<typeof RoundPlayerResult>;

export const RoundResult = __t.object("RoundResult", {
  id: __t.u64(),
  matchId: __t.u64(),
  roundIndex: __t.i32(),
  userId: __t.u64(),
  points: __t.f64(),
  elapsedMs: __t.option(__t.f64()),
  solved: __t.bool(),
  attempts: __t.i32(),
  lockedUntil: __t.option(__t.timestamp()),
  passed: __t.bool(),
});
export type RoundResult = __Infer<typeof RoundResult>;

export const RoundReveal = __t.object("RoundReveal", {
  id: __t.u64(),
  matchId: __t.u64(),
  roundIndex: __t.i32(),
  previewUrl: __t.string(),
  title: __t.option(__t.string()),
  artist: __t.option(__t.string()),
  artworkUrl: __t.option(__t.string()),
  categoryName: __t.option(__t.string()),
  revealedAt: __t.option(__t.timestamp()),
});
export type RoundReveal = __Infer<typeof RoundReveal>;

export const RoundStatus = __t.object("RoundStatus", {
  matchId: __t.u64(),
  roundIndex: __t.i32(),
  solved: __t.bool(),
  attempts: __t.i32(),
  attemptsRemaining: __t.i32(),
  lockedUntil: __t.option(__t.timestamp()),
  pointsThisRound: __t.f64(),
  passed: __t.bool(),
});
export type RoundStatus = __Infer<typeof RoundStatus>;

export const Settings = __t.object("Settings", {
  id: __t.u64(),
  currentVersionId: __t.option(__t.u64()),
  devFeaturesEnabled: __t.bool(),
  updatedAt: __t.timestamp(),
  updatedBy: __t.option(__t.u64()),
});
export type Settings = __Infer<typeof Settings>;

export const Track = __t.object("Track", {
  id: __t.u64(),
  itunesTrackId: __t.i64(),
  title: __t.string(),
  titleNormalized: __t.string(),
  artist: __t.string(),
  artistNormalized: __t.string(),
  artworkUrl: __t.string(),
  previewUrl: __t.string(),
  previewCheckedAt: __t.timestamp(),
  categoryIds: __t.array(__t.u64()),
  difficulty: __t.i32(),
  popularity: __t.i32(),
  releaseYear: __t.i32(),
  playable: __t.bool(),
  medianSolveMs: __t.option(__t.f64()),
  solveSampleCount: __t.i32(),
});
export type Track = __Infer<typeof Track>;

export const TrackAlias = __t.object("TrackAlias", {
  id: __t.u64(),
  trackId: __t.u64(),
  aliasNormalized: __t.string(),
});
export type TrackAlias = __Infer<typeof TrackAlias>;

export const TrackIndex = __t.object("TrackIndex", {
  id: __t.u64(),
  titles: __t.array(__t.string()),
  truncated: __t.bool(),
  trackCount: __t.i32(),
  builtAt: __t.timestamp(),
});
export type TrackIndex = __Infer<typeof TrackIndex>;

export const TrackInput = __t.object("TrackInput", {
  itunesTrackId: __t.i64(),
  title: __t.string(),
  titleNormalized: __t.string(),
  artist: __t.string(),
  artistNormalized: __t.string(),
  artworkUrl: __t.string(),
  previewUrl: __t.string(),
  categorySlugs: __t.array(__t.string()),
  difficulty: __t.i32(),
  popularity: __t.i32(),
  releaseYear: __t.i32(),
  playable: __t.bool(),
});
export type TrackInput = __Infer<typeof TrackInput>;

export const TutorialClip = __t.object("TutorialClip", {
  title: __t.string(),
  artist: __t.string(),
  artworkUrl: __t.string(),
  previewUrl: __t.string(),
});
export type TutorialClip = __Infer<typeof TutorialClip>;

export const TutorialTrack = __t.object("TutorialTrack", {});
export type TutorialTrack = __Infer<typeof TutorialTrack>;

export const User = __t.object("User", {
  id: __t.u64(),
  handle: __t.string(),
  displayName: __t.string(),
  avatarUrl: __t.option(__t.string()),
  avatarHidden: __t.bool(),
  elo: __t.i32(),
  gamesPlayed: __t.i32(),
  placementsRemaining: __t.i32(),
  createdAt: __t.timestamp(),
  role: __t.option(__t.string()),
  xp: __t.f64(),
  level: __t.i32(),
  rankedWins: __t.i32(),
  snapGuesses: __t.i32(),
  onboardedAt: __t.option(__t.timestamp()),
  welcomeStep: __t.option(__t.i32()),
  tutorialCompletedAt: __t.option(__t.timestamp()),
  bio: __t.option(__t.string()),
  bioHidden: __t.bool(),
  isBot: __t.bool(),
  botPersonaId: __t.option(__t.string()),
  lastPracticePersonaId: __t.option(__t.string()),
  isGuest: __t.bool(),
  guestClaimedAt: __t.option(__t.timestamp()),
  guestClaimToken: __t.option(__t.string()),
});
export type User = __Infer<typeof User>;

export const UserAvatar = __t.object("UserAvatar", {
  userId: __t.u64(),
  mimeType: __t.string(),
  data: __t.byteArray(),
  version: __t.i32(),
  uploadedAt: __t.timestamp(),
});
export type UserAvatar = __Infer<typeof UserAvatar>;

export const UserBadge = __t.object("UserBadge", {
  id: __t.u64(),
  userId: __t.u64(),
  badgeId: __t.string(),
  earnedAt: __t.timestamp(),
});
export type UserBadge = __Infer<typeof UserBadge>;

export const UserPreference = __t.object("UserPreference", {
  userId: __t.u64(),
  preferredCategoryIds: __t.array(__t.u64()),
});
export type UserPreference = __Infer<typeof UserPreference>;

export const XpAward = __t.object("XpAward", {
  reason: __t.string(),
  amount: __t.f64(),
});
export type XpAward = __Infer<typeof XpAward>;

