// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  handle: __t.string(),
  displayName: __t.string().name("display_name"),
  avatarUrl: __t.option(__t.string()).name("avatar_url"),
  avatarHidden: __t.bool().name("avatar_hidden"),
  elo: __t.i32(),
  gamesPlayed: __t.i32().name("games_played"),
  placementsRemaining: __t.i32().name("placements_remaining"),
  createdAt: __t.timestamp().name("created_at"),
  role: __t.option(__t.string()),
  xp: __t.f64(),
  level: __t.i32(),
  rankedWins: __t.i32().name("ranked_wins"),
  snapGuesses: __t.i32().name("snap_guesses"),
  onboardedAt: __t.option(__t.timestamp()).name("onboarded_at"),
  welcomeStep: __t.option(__t.i32()).name("welcome_step"),
  tutorialCompletedAt: __t.option(__t.timestamp()).name("tutorial_completed_at"),
  bio: __t.option(__t.string()),
  bioHidden: __t.bool().name("bio_hidden"),
  isBot: __t.bool().name("is_bot"),
  botPersonaId: __t.option(__t.string()).name("bot_persona_id"),
  lastPracticePersonaId: __t.option(__t.string()).name("last_practice_persona_id"),
  isGuest: __t.bool().name("is_guest"),
  guestClaimedAt: __t.option(__t.timestamp()).name("guest_claimed_at"),
  guestClaimToken: __t.option(__t.string()).name("guest_claim_token"),
});
