// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ClaimGuestRunsReducer from "../claim_guest_runs_reducer";
import CompleteDailyReducer from "../complete_daily_reducer";
import CompleteOnboardingReducer from "../complete_onboarding_reducer";
import CreateRoomReducer from "../create_room_reducer";
import DequeueReducer from "../dequeue_reducer";
import DevResolveNowReducer from "../dev_resolve_now_reducer";
import EnqueueReducer from "../enqueue_reducer";
import EnsureUserReducer from "../ensure_user_reducer";
import ForfeitDailyReducer from "../forfeit_daily_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import NudgeReducer from "../nudge_reducer";
import PassRoundReducer from "../pass_round_reducer";
import ProbeHandleReducer from "../probe_handle_reducer";
import PurgeDevRankBotsReducer from "../purge_dev_rank_bots_reducer";
import RebuildTitleIndexReducer from "../rebuild_title_index_reducer";
import RemoveAuthIssuerReducer from "../remove_auth_issuer_reducer";
import ReportProfileReducer from "../report_profile_reducer";
import ReportReadyReducer from "../report_ready_reducer";
import ResetConfigReducer from "../reset_config_reducer";
import ReturnToLobbyReducer from "../return_to_lobby_reducer";
import RevertConfigReducer from "../revert_config_reducer";
import SaveConfigReducer from "../save_config_reducer";
import SeedBotsReducer from "../seed_bots_reducer";
import SeedDevRankBotsReducer from "../seed_dev_rank_bots_reducer";
import SetAuthIssuerReducer from "../set_auth_issuer_reducer";
import SetAvatarImageReducer from "../set_avatar_image_reducer";
import SetDevFeaturesReducer from "../set_dev_features_reducer";
import SetHandleReducer from "../set_handle_reducer";
import SetRoleReducer from "../set_role_reducer";
import SetRoomReadyReducer from "../set_room_ready_reducer";
import SetWelcomeStepReducer from "../set_welcome_step_reducer";
import StartDailyReducer from "../start_daily_reducer";
import StartPracticeReducer from "../start_practice_reducer";
import StartRoomMatchReducer from "../start_room_match_reducer";
import SubmitBanReducer from "../submit_ban_reducer";
import SubmitGuessReducer from "../submit_guess_reducer";
import SurrenderReducer from "../surrender_reducer";
import UpdateProfileReducer from "../update_profile_reducer";
import UpsertCategoriesReducer from "../upsert_categories_reducer";
import UpsertTracksReducer from "../upsert_tracks_reducer";

export type ClaimGuestRunsParams = __Infer<typeof ClaimGuestRunsReducer>;
export type CompleteDailyParams = __Infer<typeof CompleteDailyReducer>;
export type CompleteOnboardingParams = __Infer<typeof CompleteOnboardingReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type DequeueParams = __Infer<typeof DequeueReducer>;
export type DevResolveNowParams = __Infer<typeof DevResolveNowReducer>;
export type EnqueueParams = __Infer<typeof EnqueueReducer>;
export type EnsureUserParams = __Infer<typeof EnsureUserReducer>;
export type ForfeitDailyParams = __Infer<typeof ForfeitDailyReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type NudgeParams = __Infer<typeof NudgeReducer>;
export type PassRoundParams = __Infer<typeof PassRoundReducer>;
export type ProbeHandleParams = __Infer<typeof ProbeHandleReducer>;
export type PurgeDevRankBotsParams = __Infer<typeof PurgeDevRankBotsReducer>;
export type RebuildTitleIndexParams = __Infer<typeof RebuildTitleIndexReducer>;
export type RemoveAuthIssuerParams = __Infer<typeof RemoveAuthIssuerReducer>;
export type ReportProfileParams = __Infer<typeof ReportProfileReducer>;
export type ReportReadyParams = __Infer<typeof ReportReadyReducer>;
export type ResetConfigParams = __Infer<typeof ResetConfigReducer>;
export type ReturnToLobbyParams = __Infer<typeof ReturnToLobbyReducer>;
export type RevertConfigParams = __Infer<typeof RevertConfigReducer>;
export type SaveConfigParams = __Infer<typeof SaveConfigReducer>;
export type SeedBotsParams = __Infer<typeof SeedBotsReducer>;
export type SeedDevRankBotsParams = __Infer<typeof SeedDevRankBotsReducer>;
export type SetAuthIssuerParams = __Infer<typeof SetAuthIssuerReducer>;
export type SetAvatarImageParams = __Infer<typeof SetAvatarImageReducer>;
export type SetDevFeaturesParams = __Infer<typeof SetDevFeaturesReducer>;
export type SetHandleParams = __Infer<typeof SetHandleReducer>;
export type SetRoleParams = __Infer<typeof SetRoleReducer>;
export type SetRoomReadyParams = __Infer<typeof SetRoomReadyReducer>;
export type SetWelcomeStepParams = __Infer<typeof SetWelcomeStepReducer>;
export type StartDailyParams = __Infer<typeof StartDailyReducer>;
export type StartPracticeParams = __Infer<typeof StartPracticeReducer>;
export type StartRoomMatchParams = __Infer<typeof StartRoomMatchReducer>;
export type SubmitBanParams = __Infer<typeof SubmitBanReducer>;
export type SubmitGuessParams = __Infer<typeof SubmitGuessReducer>;
export type SurrenderParams = __Infer<typeof SurrenderReducer>;
export type UpdateProfileParams = __Infer<typeof UpdateProfileReducer>;
export type UpsertCategoriesParams = __Infer<typeof UpsertCategoriesReducer>;
export type UpsertTracksParams = __Infer<typeof UpsertTracksReducer>;

