// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CompleteOnboardingReducer from "../complete_onboarding_reducer";
import EnsureUserReducer from "../ensure_user_reducer";
import NudgeReducer from "../nudge_reducer";
import PassRoundReducer from "../pass_round_reducer";
import ProbeHandleReducer from "../probe_handle_reducer";
import RebuildTitleIndexReducer from "../rebuild_title_index_reducer";
import RemoveAuthIssuerReducer from "../remove_auth_issuer_reducer";
import ReportReadyReducer from "../report_ready_reducer";
import ResetConfigReducer from "../reset_config_reducer";
import RevertConfigReducer from "../revert_config_reducer";
import SaveConfigReducer from "../save_config_reducer";
import SetAuthIssuerReducer from "../set_auth_issuer_reducer";
import SetDevFeaturesReducer from "../set_dev_features_reducer";
import SetHandleReducer from "../set_handle_reducer";
import SetRoleReducer from "../set_role_reducer";
import SetWelcomeStepReducer from "../set_welcome_step_reducer";
import SubmitGuessReducer from "../submit_guess_reducer";
import UpdateProfileReducer from "../update_profile_reducer";
import UpsertCategoriesReducer from "../upsert_categories_reducer";
import UpsertTracksReducer from "../upsert_tracks_reducer";

export type CompleteOnboardingParams = __Infer<typeof CompleteOnboardingReducer>;
export type EnsureUserParams = __Infer<typeof EnsureUserReducer>;
export type NudgeParams = __Infer<typeof NudgeReducer>;
export type PassRoundParams = __Infer<typeof PassRoundReducer>;
export type ProbeHandleParams = __Infer<typeof ProbeHandleReducer>;
export type RebuildTitleIndexParams = __Infer<typeof RebuildTitleIndexReducer>;
export type RemoveAuthIssuerParams = __Infer<typeof RemoveAuthIssuerReducer>;
export type ReportReadyParams = __Infer<typeof ReportReadyReducer>;
export type ResetConfigParams = __Infer<typeof ResetConfigReducer>;
export type RevertConfigParams = __Infer<typeof RevertConfigReducer>;
export type SaveConfigParams = __Infer<typeof SaveConfigReducer>;
export type SetAuthIssuerParams = __Infer<typeof SetAuthIssuerReducer>;
export type SetDevFeaturesParams = __Infer<typeof SetDevFeaturesReducer>;
export type SetHandleParams = __Infer<typeof SetHandleReducer>;
export type SetRoleParams = __Infer<typeof SetRoleReducer>;
export type SetWelcomeStepParams = __Infer<typeof SetWelcomeStepReducer>;
export type SubmitGuessParams = __Infer<typeof SubmitGuessReducer>;
export type UpdateProfileParams = __Infer<typeof UpdateProfileReducer>;
export type UpsertCategoriesParams = __Infer<typeof UpsertCategoriesReducer>;
export type UpsertTracksParams = __Infer<typeof UpsertTracksReducer>;

